"""data entry.

Revision ID: 9358f5018552
Revises:
Create Date: 2025-06-17 20:55:27.364024

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '9358f5018552'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'data_entry',
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('version', sa.String(length=50), nullable=False),
        sa.Column('desc', sa.Text(), nullable=False),
        sa.Column('country', sa.SmallInteger(), nullable=False),
        sa.Column('count', sa.Integer(), nullable=False),
        sa.Column('parent', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('pk', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('pk'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_entry')
    # ### end Alembic commands ###
